language: cpp
complier:
    - clang
    - gcc
script:
    - wget "https://www.cs.umd.edu/~mount/ANN/Files/1.1.2/ann_1.1.2.zip"
    - unzip ./ann_1.1.2.zip
    - make linux-g++
    - make ms
    - make example
