language: cpp
complier:
    - clang
    - gcc
script:
    - wget "https://www.cs.umd.edu/~mount/ANN/Files/1.1.2/ann_1.1.2.zip"
    - unzip ./ann_1.1.2.zip
    - cd ann_1.1.2
    - make linux-g++
    - mv ann_1.1.2 ann
    - cd ..
    - make ms
    - make example
